# Main entrypoint of the workflow.
# Please follow the best practices:
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there.


from pathlib import Path

# absolute path to snakemake dir
snakemake_dir = Path(workflow.snakefile).parent.resolve()


# include default config values
configfile: f"{snakemake_dir.parent}/config/default_config.yaml"

# define main database folder
if config["database_dir"]=="databases":
    logger.error("database folder is 'databases', you should choose another in the config file")
DB_DIR = Path(config["database_dir"])

BBTOOLS_WRAPPER = "v3.3.3/bio/bbtools"


include: "rules/input_functions.smk"
# include: "rules/trimming.smk"


include: "rules/qc.smk"
get_screen_input_fastq = rules.quality_trimming.output.out

include: "rules/screen.smk"
include: "rules/decontamination.smk"


rule all:
    input:
        #"reports/trimming/multiqc.html",
        expand(
            "QC/reads/{sample}_{fraction}.fastq.gz", fraction=FRACTIONS, sample=SAMPLES
        ),
        expand( "Intermediate/stats/qc/{sample}/insert_sizes.txt", sample=SAMPLES
        ),
        expand( "Intermediate/stats/qc/{sample}/quality_boxplots.txt", sample=SAMPLES
        ),
        

       
