# Main entrypoint of the workflow.
# Please follow the best practices:
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there.


from pathlib import Path

# absolute path to snakemake dir
snakemake_dir = Path(workflow.snakefile).parent.resolve()


# include default config values
configfile: f"{snakemake_dir.parent}/config/default_config.yaml"


# define main database folder
if config["database_dir"] == "databases":
    logger.error(
        "database folder is 'databases', you should choose another in the config file"
    )
DB_DIR = Path(config["database_dir"])

BBTOOLS_WRAPPER = "v3.3.3/bio/bbtools"


include: "rules/input_functions.smk"
include: "rules/trimming.smk"


# include: "rules/qc.smk"


get_screen_input_fastq = get_quality_controlled_reads


include: "rules/screen.smk"
include: "rules/decontamination.smk"


rule all:
    input:
        expand(
            "QC/reads/{sample}_{fraction}.fastq.gz", fraction=FRACTIONS, sample=SAMPLES
        ),
        #expand("Intermediate/stats/qc/{sample}/insert_sizes.txt", sample=SAMPLES),
        #expand("Intermediate/stats/qc/{sample}/gc_histogram.txt", sample=SAMPLES),
        "Intermediate/reports/decontamination_stats.csv",
        "reports/quality_trimming/multiqc.html",


### pepulate resources for rules that don't have

for r in workflow.rules:


    if not "runtime" in r.resources:
        r.resources["runtime"] = r.resources["time_min"]
