# Use this file to define all default values

threads_simple: 2
threads: 8

mem_simple: 1000
mem_default: 40000

importqc_params: "iupacToN=t touppercase=t qout=33 addslash=t trimreaddescription=t"

trim_mean_quality: 15
trim_base_phred: 8
trim_min_length: 31
