# We use the Portable Encapsulated Projects (PEP) standard
# See more on https://pep.databio.org/

pep_version: 2.0.0
# path to the sample table relative to the config file
sample_table: "sample_table.csv"

sample_modifiers:
  append:
    fastq_dir: "/Users/silas/Documents/test_reads/"
  derive:
    attributes: [Reads_raw_R1, Reads_raw_R1]
    sources:
      key1: "{fastq_dir}/{R1}"
      key2: "{fastq_dir}/{R2}"
